In [1]:
from __future__ import print_function
import numpy as np
from numpy.random import RandomState
import pickle
import os
import pandas as pd
from sklearn import preprocessing
import skfuzzy as fuzz
import itertools
from operator import add
import operator

In [24]:
def common_data(list1, list2): 
    result = False
  
    # traverse in the 1st list 
    for x in list1: 
  
        # traverse in the 2nd list 
        for y in list2: 
    
            # if one common 
            if x == y: 
                result = True
                return result  
                  
    return result 
def getSortedServicesList(dfMatrix, columns):
    similar_services = dfMatrix 
    similar_dict = similar_services.to_dict('index')
    topk_similar_dict = []
    for s_dict in columns:
        del similar_dict[s_dict][s_dict]
        sorted_services = sorted(similar_dict[s_dict].items(), key=operator.itemgetter(1),reverse=True)
        topk_similar_dict.append(sorted_services)
    return topk_similar_dict
def getClusterIndex(service):
    for c in range(len(finalClusters)):
        if service in finalClusters[c]:
            return c

In [4]:
data = np.loadtxt('rtMatrix.txt')
df = pd.DataFrame(data)

In [5]:
dft = df.transpose()
corr = dft.corr()
x = corr.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
corr = pd.DataFrame(x_scaled)
#corr.to_csv (r'C:\Users\Noor Ul Ain\NeighboringUsers\User_similarity_PCC_5825.csv', index = None, header=True)

In [6]:
arrayUsers = []
with open("userlist.txt", 'r') as file:
    for line in file:
        arrayUsers.append(line)
fileUsers = []
for item in arrayUsers:
    fileUsers.append(item.split('\t'))
fileUsers = fileUsers[2:]
usersPd = pd.DataFrame(fileUsers)

In [7]:
topUsersAS = []
topUsersCountry = []
for item in fileUsers:
    topUsersAS.append(usersPd[usersPd[4]==usersPd.iloc[int(item[0])][4]][0].values.tolist())
    topUsersCountry.append(usersPd[usersPd[2]==usersPd.iloc[int(item[0])][2]][0].values.tolist())
topUsersAS.sort()
topUsersAS=list(topUsersAS for topUsersAS,_ in itertools.groupby(topUsersAS))
topUsersCountry.sort()
topUsersCountry= list(topUsersCountry for topUsersCountry,_ in itertools.groupby(topUsersCountry))

In [8]:

simiUsersListAS = []
simiUsersListCon = []
for item in range(len(topUsersAS)):
    if len(topUsersAS[item])>9:
        simiUsersListAS.append(topUsersAS[item])
        
for item in range(len(topUsersCountry)):
    if len(topUsersCountry[item])>9:
        simiUsersListCon.append(topUsersCountry[item])

In [9]:
pdAS = pd.DataFrame(simiUsersListAS)
pdCountry = pd.DataFrame(simiUsersListCon)
remainingUsers = [x for x in range(339)]

In [10]:
simiUsersListConInt = []
for i in simiUsersListCon:
    simiUsersListConInt.append([int(x) for x in i])

In [11]:
similar_users_As = pd.read_csv(r'C:\Users\noor.ulain3\NeighboringUsers\NeighboringUsers\Neighbors_AS.csv') 
similar_users_As = np.asarray(similar_users_As)
dftAs = dft[similar_users_As[0]]

similar_users_Con = pd.read_csv(r'C:\Users\noor.ulain3\NeighboringUsers\NeighboringUsers\Neighbors_Country.csv') 
similar_users_Con = np.asarray(similar_users_Con)
dftCon = dft[similar_users_As[0]]
corrCon = dftCon.corr()

In [12]:
simiUsersListConInt
simiUsersListAS = similar_users_As.tolist()

In [13]:
simiUsersListConUnique = []
for item in simiUsersListConInt:
    simiUsersListConUnique.append([x for x in item if x not in simiUsersListAS[0]])

In [14]:
finalClusters = []
finalClusters.append(simiUsersListAS[0])
for item in simiUsersListConUnique:
    finalClusters.append(item)

In [15]:
for item in finalClusters:
    for i in item:
        remainingUsers.remove(i)

In [16]:
finalClusters.append(remainingUsers)

In [17]:
len(finalClusters)

7

In [42]:
neighbours=[]

In [46]:
for i in range(339):
    c = getClusterIndex(i)
    neighbours.append(sort_list_dict[c][finalClusters[c].index(i)][:10])

In [18]:
corrAs = dftAs.corr()
x = corrAs.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
corrAs = pd.DataFrame(x_scaled)
similar_users_As_array = np.asarray(corrAs)
topk_users_dict = []
for i in range(len(similar_users_As_array)):
    user_dict = {k: v for k, v in enumerate(similar_users_As_array[i]) if i!=k}
    sorted_user = sorted(user_dict.items(), key=operator.itemgetter(1),reverse=True)
    topk_users_dict.append(sorted_user[:10])

In [19]:
########finding neighbours#######
simiDfList = []
for c in range(len(finalClusters)):
    temp = corr[finalClusters[c]]
    simiDfList.append(temp.iloc[finalClusters[c]])

In [20]:
sort_list_dict = []
for i in range(len(simiDfList)):
    sort_list_dict.append(getSortedServicesList(simiDfList[i], finalClusters[i]))

In [21]:
len(sort_list_dict)

7

In [ ]:
 sort_list_dict[c][finalClusters[c].tolist().index(i)][:10]

In [42]:
real_topk_users_dict = []
for userdict in topk_users_dict:
    real_topk_users = {}
    for user in userdict:
        real_topk_users.update({similar_users_As[0][user[0]]:user[1]})
    real_topk_users_dict.append(real_topk_users)


[['78',
  '79',
  '83',
  '97',
  '98',
  '99',
  '118',
  '119',
  '132',
  '133',
  '148',
  '149',
  '150',
  '151',
  '152',
  '153',
  '167',
  '168',
  '174',
  '175',
  '176',
  '177',
  '235',
  '236',
  '261',
  '262',
  '263',
  '284',
  '285',
  '328',
  '329']]

In [45]:
similar_users_Con

array([[  0.,   1.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
         23.,  24.,  25.,  26.,  27.,  28.,  32.,  33.,  34.,  35.,  36.,
         37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,
         48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,
         59.,  60.,  61.,  62.,  63.,  64.,  65.,  68.,  71.,  72.,  73.,
         74.,  93.,  94.,  95.,  96., 100., 101., 102., 103., 106., 107.,
        108., 109., 125., 126., 127., 128., 134., 136., 137., 140., 141.,
        162., 163., 164., 165., 166., 169., 170., 171., 172., 173., 185.,
        191., 198., 199., 202., 203., 206., 207., 209., 210., 218., 219.,
        220., 221., 222., 223., 224., 225., 226., 227., 228., 229., 230.,
        231., 232., 233., 244., 245., 246., 247., 248., 249., 286., 287.,
        288., 289., 290., 293., 294., 295., 308., 309., 310., 311., 312.,
        313., 314., 315., 317., 318., 

In [27]:
  def getTopKUsersRegularizationLocationBased():
        similar_users_As = pd.read_csv(r'C:\Users\noor.ulain3\NeighboringUsers\NeighboringUsers\Neighbors_AS.csv') 
        similar_users_As = np.asarray(similar_users_As)
        gradTopKU =[]
        topk_users_dict = self.topk_UsersDict
        value = 0.0
        for i in range(339):
            if i in similar_users_As[0]:
                dftAs = dft[similar_users_As[0]]
                corrAs = dftAs.corr()
                x = corrAs.values #returns a numpy array
                min_max_scaler = preprocessing.MinMaxScaler()
                x_scaled = min_max_scaler.fit_transform(x)
                corrAs = pd.DataFrame(x_scaled)
                similar_users_As_array = np.asarray(corrAs)
                topk_users_dict = []
                for i in range(len(similar_users_As_array)):
                    user_dict = {k: v for k, v in enumerate(similar_users_As_array[i]) if i!=k}
                    sorted_user = sorted(user_dict.items(), key=operator.itemgetter(1),reverse=True)
                    topk_users_dict.append(sorted_user[:10])
                real_topk_users_dict = []
                for userdict in topk_users_dict:
                    real_topk_users = {}
                    for user in userdict:
                        real_topk_users.update({similar_users_As[0][user[0]]:user[1]})
                    real_topk_users_dict.append(real_topk_users)

                
            iTopkUsers=topk_users_dict[i]
            for user in iTopkUsers:
                gradTopKU.append(np.sum(user[1]*(np.square(self.U[i]-self.U[user[0]]))))


In [28]:
getTopKUsersRegularizationLocationBased()

NameError: name 'self' is not defined

In [61]:
similar_users_As[0][topk_users_dict[0][0][0]]

149

In [60]:
similar_users_As

array([[ 78,  79,  83,  97,  98,  99, 118, 119, 132, 133, 148, 149, 150,
        151, 152, 153, 167, 168, 174, 175, 176, 177, 235, 236, 261, 262,
        263, 284, 285, 328, 329]], dtype=int64)

In [49]:
dictionary = { 7: 'one', 2:'two', 3:'three' }

#corr.to_csv (r'C:\Users\Noor Ul Ain\services_similarity_matrix\User_similarity_matrix_Full.csv', index = None, header=True)

In [ ]:
dictionary['ONE'] = dictionary['']

In [50]:
dictionary.pop(7)

'one'

In [11]:
def getTopUsers(topK, user):
        similar_users_As = pd.read_csv(r'C:\Users\nain\NeighboringUsers\Neighbors_AS.csv') 
        similar_users_As = np.asarray(similar_users_As)
        if user in similar_users_As[0]:
            
        similar_users = pd.read_csv(r'C:\Users\nain\NeighboringUsers\User_similarity_PCC_5825.csv') 
        similar_users = np.asarray(similar_users)
        topk_users_dict = []
        for i in range(len(similar_users)):
            user_dict = {k: v for k, v in enumerate(similar_users[i]) if i!=k}
            sorted_user = sorted(user_dict.items(), key=operator.itemgetter(1),reverse=True)
            topk_users_dict.append(sorted_user[:topK])
        return(topk_users_dict)

IndentationError: expected an indented block (<ipython-input-11-b29324ed537c>, line 6)

In [12]:

#if user in similar_users_As[0]:
    

In [13]:
similar_users_As


array([[ 78,  79,  83,  97,  98,  99, 118, 119, 132, 133, 148, 149, 150,
        151, 152, 153, 167, 168, 174, 175, 176, 177, 235, 236, 261, 262,
        263, 284, 285, 328, 329]], dtype=int64)

In [217]:
{k: v for k, v in enumerate(np.asarray(corr) )if i!=k}

{0: array([1.        , 0.57804345, 0.31279915, 0.28723214, 0.39756786,
        0.47544423, 0.36489465, 0.38375321, 0.60501233, 0.58226259,
        0.43666914, 0.70999956, 0.50881741, 0.53774319, 0.66435332,
        0.58430728, 0.50934691, 0.59904132, 0.35419064, 0.18629892,
        0.38429405, 0.35294191, 0.30385837, 0.37381045, 0.35007406,
        0.        , 0.19950228, 0.02167025, 0.0123381 , 0.28170501,
        0.27762407]),
 1: array([0.60551027, 1.        , 0.38478663, 0.30638363, 0.39524695,
        0.45409018, 0.39891314, 0.42723726, 0.63949381, 0.50453656,
        0.37990837, 0.56457375, 0.46053315, 0.49455003, 0.63545981,
        0.4998725 , 0.50021341, 0.50540497, 0.39714977, 0.22795182,
        0.39371667, 0.32917975, 0.38909636, 0.40838341, 0.40883886,
        0.02231835, 0.1919107 , 0.0898748 , 0.07662892, 0.28386945,
        0.3119862 ]),
 2: array([0.39644492, 0.42204901, 1.        , 0.48665125, 0.42332576,
        0.46328911, 0.51793778, 0.57250865, 0.47396023, 0.41355

<bound method DataFrame.to_dict of           0         1         2         3         4         5         6   \
0   1.000000  0.578043  0.312799  0.287232  0.397568  0.475444  0.364895   
1   0.605510  1.000000  0.384787  0.306384  0.395247  0.454090  0.398913   
2   0.396445  0.422049  1.000000  0.486651  0.423326  0.463289  0.517938   
3   0.404734  0.380396  0.511862  1.000000  0.402761  0.409631  0.475617   
4   0.454427  0.414192  0.405376  0.352365  1.000000  0.725745  0.490491   
5   0.530431  0.477290  0.452966  0.367197  0.728908  1.000000  0.455219   
6   0.426708  0.419638  0.504550  0.433219  0.492148  0.450656  1.000000   
7   0.408247  0.411709  0.532610  0.452245  0.442831  0.470924  0.737300   
8   0.616323  0.625435  0.418208  0.355330  0.366411  0.433816  0.402022   
9   0.592127  0.482554  0.348052  0.316082  0.419177  0.454653  0.383853   
10  0.449078  0.351345  0.530446  0.436161  0.522080  0.490494  0.490415   
11  0.706377  0.528439  0.275544  0.263076  0.429011 